### ISSUE TITLE
Deprecate moveit_metapackages repo

### ISSUE THREAD

**Issue by 130s** [ros-planning/moveit_metapackages#11]
- For Indigo, multiple repos host metapackages for MoveIt! core libraries.
  - `moveit` in `moveit` repo.
  - `moveit_full/_pr2` in `moveit_metapackages` repo.
- For Jade onward, we won't release `moveit_full/_pr2` metapackages https://github.com/ros-planning/moveit_ros/issues/692#issuecomment-238719902

Why not deprecate this repo and move all existing metapackages to `indigo-devel` branch on `moveit` repo?

Moving metapackages into `moveit` repo can also prevent release maintainers from working on two different releases.

Steps to be made:

1. [x] Merge existing PR (currently only #10)
1. [x] Import all the existing metapackages on this repo into the top level dir of `moveit` repo. --> I https://github.com/ros-planning/moveit/pull/422, JK https://github.com/ros-planning/moveit/issues/436
1. [x] Deprecate notice for this repo (well actually deprecated notice is already posted at the top page of this repo).
1. [ ] Open a new PR on rosdistro to move all the existing metapackages into the entry that is rooted on `moveit` repo. --> https://github.com/ros/rosdistro/pull/13767 --> NG. Need to `bloom` https://github.com/ros-planning/moveit_metapackages/issues/11#issuecomment-277731406

**Comment by 130s** [comment]
Moving metapackages into `moveit` repo can also prevent release maintainers from working on two different releases.

**Comment by v4hn** [comment]
Sounds reasonable enough. +1 if it simplifies the release process.
I'm not yet convinced boiling down everything into one meta-package only is a wise decision.
At least it looks like we'll have another robot-specific package again in the future. ;)

**Comment by davetcoleman** [comment]
+1 to more repo consolidation into ``moveit`` :)

**Comment by 130s** [comment]
Steps to be made:

1. [ ] Merge existing PR (currently only #10)
1. [ ] Import all the existing metapackages on this repo into the top level dir of `moveit` repo.
1. [ ] Deprecate notice for this repo (well actually deprecated notice is already posted at the top page of this repo).
1. [ ] Open a new PR on rosdistro to move all the existing metapackages into the entry that is rooted on `moveit` repo.

**Comment by 130s** [comment]
>  I'm not yet convinced boiling down everything into one meta-package only is a wise decision.

I may have given you a wrong impression? My suggestion for meta packages and their location looks like the following:
```
moveit repo
|- moveit
|- moveit_full
|- moveit_full_pr2
|- (moveit_runtime once #10 merged)
|- (more if needed)
:
|- moveit_commander
|- (other non-meta packages)
```

**Comment by v4hn** [comment]
That's fine. Feel free to go ahead with this when you get around to do so..

**Comment by 130s** [comment]
> - [ ] Open a new PR on rosdistro to move all the existing metapackages into the entry that is rooted on moveit repo. --> https://github.com/ros/rosdistro/pull/13767

As I left comment in the linked PR, I need to run `bloom` to complete moving the packages to another repo, which I'll work on shortly.

**Comment by 130s** [comment]
> 1. [ ] Open a new PR on rosdistro to move all the existing metapackages into the entry that is rooted on `moveit` repo. --> https://github.com/ros/rosdistro/pull/13767 --> NG. Need to `bloom` https://github.com/ros-planning/moveit_metapackages/issues/11#issuecomment-277731406

Done via:
- I https://github.com/ros/rosdistro/pull/13810, https://github.com/ros/rosdistro/pull/13811
- J https://github.com/ros/rosdistro/pull/13813
- K https://github.com/ros/rosdistro/pull/13809
